apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-express-dpl
  labels:
    app: docker-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-express
  template:
    metadata:
      labels:
        app: docker-express
    spec:
      containers:
        - name: docker-express-ctr
          image: noudadrichem/docker-express
          ports:
            - containerPort: 5000
        