apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-express-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - 
    http:
      paths:
        - path: /
          backend:
            serviceName: docker-express-svc
            servicePort: 80