apiVersion: v1
kind: Service
metadata:
  name: docker-express-svc
spec:
  selector:
    app: docker-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000