apiVersion: v1
kind: Service
metadata:
  name: barfoo-svc
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 5000
  - port: 443
    name: https
    targetPort: 5000
  selector:
    app: barfoo